# Deployment MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      version: "1"
  template:
    metadata:
      labels:
        app: mongodb
        version: "1"
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd

---

# Service MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
    version: "1"
  ports:
  - port: 27017
  type: ClusterIP

---

# Application Web Rotten Potatoes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
      version: "1"
  template:
    metadata:
      labels:
        app: web
        version: "1"
    spec:
      containers:
      - name: web
        image: paulopkl/rotten-potatoes:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB # => Nome do database
          value: admin
        - name: MONGODB_HOST # => Host do MongoDB
          value: mongodb
        - name: MONGODB_PORT # => Posta de acesso ao MongoDB
          value: "27017"
        - name: MONGODB_USERNAME # => Usuário do MongoDB
          value: mongouser
        - name: MONGODB_PASSWORD # => Senha do MongoDB
          value: mongopwd

---

# Service Application Web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
    version: "1"
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort